---

- hosts: all
  become: true
  tasks:


  - name: update cache and install apache2 and php packages
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes

