---

- hosts: all
  become: true
  tasks:

  - name: update repo index
    dnf:
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install apache2 package
    dnf:
      name: httpd
      state: latest
    when: ansible_distribution == "CentOS"

  - name: add php support
    dnf:
      name: php
      state: latest
    when: ansible_distribution == "CentOS"
